# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI (name workflow)

#sự kiện gì xảy ra thì nó sẽ chạy workflow này đó là như khai báo là push và pull
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
#khi có sự kiện bắt được từ on thì nó sẽ chạy jobs
jobs: #định nghĩa các công việc mà nó sẽ tự động thực hiện
  build: #có thể đổi tên tùy ý ví dụ building 

    runs-on: ubuntu-latest

    # ứng dụng sẽ chạy trên các môi trường theo version được khai báo 
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    #các bước mà github actions nó sẽ tự động thực hiện
    steps:
    - uses: actions/checkout@v4 #kéo code từ github
    - name: Use Node.js ${{ matrix.node-version }} # tên của step
      uses: actions/setup-node@v3 #tool setup node của GitHub actions
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # ta muốn github actions sẽ chạy cho ta 3 lệnh
    - run: npm ci #clean install
    - run: npm run build --if-present #chạy source code build trong file package.json
    - run: npm test #chạy test
